[[games]]
install_dir = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Poppy Playtime\\PlaytimeLauncher"
game_title = "PlaytimeLauncher"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Poppy Playtime\\WindowsNoEditor"
game_title = "WindowsNoEditor"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Zedfest"
game_title = "Zedfest"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\BronzebeardsTavern-Windows"
game_title = "BronzebeardsTavern-Windows"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Choo-Choo Charles"
game_title = "Choo-Choo Charles"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\DeadPoly"
game_title = "DeadPoly"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Estencel"
game_title = "Estencel"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Five Laps at Freddy's Demo"
game_title = "Five Laps at Freddy's Demo"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Grocery Store Simulator Prologue"
game_title = "Grocery Store Simulator Prologue"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Hellbreach Vegas"
game_title = "Hellbreach Vegas"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Hello Neighbor"
game_title = "Hello Neighbor"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Joyville"
game_title = "Joyville"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Mist of the Dark"
game_title = "Mist of the Dark"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Mutant Year Zero"
game_title = "Mutant Year Zero"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Phantom Abyss"
game_title = "Phantom Abyss"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Pizzapocalypse"
game_title = "Pizzapocalypse"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Pseudoregalia"
game_title = "Pseudoregalia"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Pumpkin Jack"
game_title = "Pumpkin Jack"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\RoboQuest"
game_title = "RoboQuest"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\SpongeBob SquarePants Battle for Bikini Bottom - Rehydrated"
game_title = "SpongeBob SquarePants Battle for Bikini Bottom - Rehydrated"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\SurrounDead"
game_title = "SurrounDead"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\The Baby In Yellow"
game_title = "The Baby In Yellow"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\TheKillingAntidotePlaytest"
game_title = "TheKillingAntidotePlaytest"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
[[games]]
install_dir = "D:\\SteamLibrary\\steamapps\\common\\Wizardry"
game_title = "Wizardry"
ue4ss_version = "latest"
installed_files = []
platform = "Other"
