[[games]]
install_dir = "/home/mythical/snap/steam/common/.steam/steam/steamapps/common/UNDEFEATED"
game_title = "UNDEFEATED"
ue4ss_version = "v3.0.1"
platform = "Other"
using_developer_version = false
show_pre_releases = false
using_keep_mods_and_settings = false

[[games]]
install_dir = "/home/mythical/snap/steam/common/.steam/steam/steamapps/common/Aero GPX/WindowsNoEditor"
game_title = "WindowsNoEditor"
ue4ss_version = "v2.5.2"
platform = "Other"
using_developer_version = false
show_pre_releases = false
using_keep_mods_and_settings = false
